apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-demo-vs
spec:
  hosts:
  - "rollout-demo.example.com"
  gateways:
  - rollout-demo-gateway
  http:
  - name: canary
    route:
    - destination:
      weight: 100
        host: rollout-demo
    - destination:
      weight: 0
        host: rollout-demo-preview
